diging/amphora

jars/cookies/templates/index.html
Added auto-focus attribute to the searchbox.
=> Updated focus variable for the search box.

jars/cookies/admin.py, jars/cookies/forms.py, jars/cookies/tests/test_bulk_upload.py
Validating that the chosen file is a ZIP file.
=> Fix for Issue #9

cookies/views_rest.py
Ensure API upload reports unauthorized when token
is missing in the upload request.
=> [JARS-90] Report unauthorized on missing token

cookies/authorization.py
Fix the bug which prevents logged in user from viewing
a public collection when the collection is not
explicitly shared with the user.
=> [JARS-84] Allow users to view public collections

cookies/views/resource.py
Fix the bug where resource's 'public' flag isn't
edited correctly.
=> [JARS-96] Correctly edit resource's 'public' flag

cookies/forms.py, cookies/templates/giles_log.html, cookies/views/giles.py
Update Giles log dashboard to support restarting of
failed Giles uploads.
=> [JARS-95] Allow user to restart failed Giles uploads

cookies/forms.py
Hardcode content type choices in the snapshot form
to avoid request time-out.
=> [JARS-109] Hardcode content type choices

cookies/views/giles.py
Temporarily enable Giles reupload for Enqueud, Sent,
and Polling states.
=> [JARS-95] Enable reupload for other states

cookies/models.py, cookies/views/resource.py, cookies/views_rest.py
=> [JARS-119] do not assume there is exactly one resource with uri

cookies/tasks.py
Fix errors reported while creating dynamic
dataset from a collection.
=> [JARS-98] Fix dynamic dataset creation errors

cookies/giles.py
Ensure duplicate content resources aren't created
post Giles upload.
=> [JARS-112] Avoid duplicate content resources

cookies/views/resource.py, cookies/views_rest.py, jars/auth.py, jars/settings.py
Support Amphora token based authentication while
accessing any page.
=> [JARS-120] Support Amphora token based auth

cookies/views/resource.py
Serve zip file content as an attachment through
Nginx.
=> [JARS-121] Serve zip file content as attachment

cookies/authorization.py, cookies/templates/collection.html, cookies/templates/fragment_resource_list.html, cookies/templates/resource.html, cookies/templatetags/authorization.py, cookies/views/resource.py
Define mapping between authorization database values
and their string counterparts used with the
template tag. Use this mapping while checking for
authorizations.
=> [JARS-122] Correctly check for authorizations

jars/settings.py
Fix CSRF errors reported while uploading resources
through the Resources REST API.
=> [JARS-123] Fix CSRF errors during API uploads

cookies/filters.py, cookies/templates/fragment_resource_list.html, cookies/views/resource.py
Don't display resource tags to reduce resource
list page load times.
=> [JARS-82] Reduce resources list page load times

cookies/views/giles.py
Fix the bug where giles log view crashes when
state isn't specified in URL parameters.
=> [JARS-106] Fix error in giles log view

cookies/accession/__init__.py, cookies/accession/giles.py, cookies/accession/hathitrust.py, cookies/aggregate.py, cookies/autocomplete.py, cookies/filters.py, cookies/forms.py, cookies/giles.py, cookies/models.py, cookies/tasks.py, cookies/templatetags/breadcrumbs.py, jars/settings.py, jars/urls.py
Fix all the warnings reported while starting Amphora.
Remove print statements. Include timestamps in Amphora
log messages.
=> [JARS-100] Fix logging output

cookies/authorization.py, cookies/forms.py, cookies/templates/giles_log.html, cookies/views/giles.py
Allow Admins and Staff to update Giles upload state.
=> [JARS-133] Support Giles uploads state change

cookies/forms.py, cookies/giles.py, cookies/templates/giles_log_item.html, cookies/templates/giles_log_item_edit.html, cookies/templates/resource.html, cookies/views/giles.py, jars/urls.py
Support manual Giles status check for individual uploads.
=> [JARS-132] Support manual Giles status check

cookies/views_rest.py
Corresponding PRs:
- Vogon Client - diging/vogon-web-client#49
- Vogon Backend - diging/vogon-web#189
=> [VGNWB-345] Add search for collections
